SERVER_PORT: '8080'
POSTGRES_DSN: 'host=localhost user=postgres password=secret dbname=ticket_db port=5432 sslmode=disable'
REDIS_ADDR: 'localhost:6379'
REDIS_PASSWORD: ''
S3_BUCKET: 'ticket-files'
S3_REGION: 'us-east-1'
AWS_ACCESS_KEY_ID: 'your-access-key'
AWS_SECRET_ACCESS_KEY: 'your-secret-key'
SMTP_HOST: 'smtp.example.com'
SMTP_PORT: 587
SMTP_USER: 'user@example.com'
SMTP_PASS: 'password'
RECAPTCHA_SECRET: 'your-recaptcha-secret'
JWT_SECRET: 'your-jwt-secret'
CLAMAV_ADDR: 'tcp://clamav:3310'
