global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8085']
    metrics_path: '/metrics'

  - job_name: 'private-service'
    static_configs:
      - targets: ['private-service:2112']
    metrics_path: '/metrics'

  - job_name: 'news-service'
    static_configs:
      - targets: ['news-service:2113']
    metrics_path: '/metrics'

  - job_name: 'ticket-service'
    static_configs:
      - targets: ['ticket-service:2114']
    metrics_path: '/metrics' 