server:
  port: ':8080'
  shutdown_timeout: 10s

database:
  host: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'postgres'
  dbname: 'ticket_service'
  sslmode: 'disable'

redis:
  host: 'localhost'
  port: '6379'
  password: ''
  db: 0

s3:
  endpoint: 'http://localhost:9000'
  access_key_id: 'minioadmin'
  secret_access_key: 'minioadmin'
  bucket_name: 'tickets'
  region: 'us-east-1'
  use_ssl: false

clamav:
  host: 'localhost'
  port: '3310'

captcha:
  secret_key: 'your-recaptcha-secret-key'
  min_score: 0.5

auth:
  jwt_secret: 'your-jwt-secret-key'
