version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - TZ=UTC
    depends_on:
      - postgres
      - redis
      - minio
      - clamav
    networks:
      - ticket-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ticket}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ticket}
      POSTGRES_DB: ${POSTGRES_DB:-ticket}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ticket-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - ticket-network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ticket-network

  clamav:
    image: clamav/clamav:latest
    ports:
      - '3310:3310'
    volumes:
      - clamav_data:/var/lib/clamav
    networks:
      - ticket-network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  clamav_data:

networks:
  ticket-network:
    driver: bridge
